version: "3.3"
services: 
    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./init-database.sh:/docker-entrypoint-initdb.d/./init-database.sh
            - ./postgres/data/:/var/lib/postgresql/data/
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "8888:8888"
        environment:
            PGADMIN_LISTEN_PORT: 8888
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        restart: unless-stopped

    rdf-extractor:
        container_name: rdf-extractor
        build: 
            context: ./src
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        environment: 
            PORT: 3000
            DB_URL: ${DB_URL}
        depends_on:
            - postgres
        # command: sh -c './wait-for postgres:5432 -- ./entrypoint.sh'
        command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; ./entrypoint.sh' 
        # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py runserver 0.0.0.0:8000'


        